{% set name = "formlayout" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/formlayout-{{ version }}.tar.gz
  sha256: 2816a408c5a78939f917dd0671b6f19e5d21aecc8f42f9a90b604a1481817e32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pyqt
    - setuptools
    - zlib
  run:
    - python >={{ python_min }}
    - pyqt
    - zlib

test:
  imports:
    - formlayout
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/PierreRaybaut/formlayout
  summary: The most easy way to create Qt form dialogs and widgets with Python
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  doc_url: https://formlayout.readthedocs.io/en/latest/
  dev_url: https://github.com/PierreRaybaut/formlayout


extra:
  recipe-maintainers:
    - xylar
